(ns expenses.controller.general-test
  (:require [midje.sweet :refer :all]
            [expenses.controller.general :as controller.general]
            [expenses.controller.revenue :as controller.revenue]
            [expenses.controller.fixed :as controller.fixed]
            [expenses.controller.purchases :as controller.purchases]))

(facts "Getting data for given year "
  (fact "Should Return income for every month"
    (controller.general/data-for-period "2020" ..db..) => {:income   [{:title  "Jan"
                                                                       :amount 0}
                                                                      {:title  "Fev"
                                                                       :amount 0}
                                                                      {:title  "Mar"
                                                                       :amount 15000}
                                                                      {:title  "Abr"
                                                                       :amount 15000}
                                                                      {:title  "Mai"
                                                                       :amount 15000}
                                                                      {:title  "Jun"
                                                                       :amount 15000}
                                                                      {:title  "Jul"
                                                                       :amount 15000}
                                                                      {:title  "Ago"
                                                                       :amount 15000}
                                                                      {:title  "Set"
                                                                       :amount 15000}
                                                                      {:title  "Out"
                                                                       :amount 15000}
                                                                      {:title  "Nov"
                                                                       :amount 19000}
                                                                      {:title  "Dez"
                                                                       :amount 12000}]
                                                           :fixed    [{:title  "Jan"
                                                                       :amount 0}
                                                                      {:title  "Fev"
                                                                       :amount 0}
                                                                      {:title  "Mar"
                                                                       :amount 15000}
                                                                      {:title  "Abr"
                                                                       :amount 15000}
                                                                      {:title  "Mai"
                                                                       :amount 15000}
                                                                      {:title  "Jun"
                                                                       :amount 15000}
                                                                      {:title  "Jul"
                                                                       :amount 15000}
                                                                      {:title  "Ago"
                                                                       :amount 15000}
                                                                      {:title  "Set"
                                                                       :amount 15000}
                                                                      {:title  "Out"
                                                                       :amount 15000}
                                                                      {:title  "Nov"
                                                                       :amount 19000}
                                                                      {:title  "Dez"
                                                                       :amount 12000}]
                                                           :expenses []
                                                           :variable [{:title  "Jan"
                                                                       :amount 0}
                                                                      {:title  "Fev"
                                                                       :amount 0}
                                                                      {:title  "Mar"
                                                                       :amount 15000}
                                                                      {:title  "Abr"
                                                                       :amount 15000}
                                                                      {:title  "Mai"
                                                                       :amount 15000}
                                                                      {:title  "Jun"
                                                                       :amount 15000}
                                                                      {:title  "Jul"
                                                                       :amount 15000}
                                                                      {:title  "Ago"
                                                                       :amount 15000}
                                                                      {:title  "Set"
                                                                       :amount 15000}
                                                                      {:title  "Out"
                                                                       :amount 15000}
                                                                      {:title  "Nov"
                                                                       :amount 19000}
                                                                      {:title  "Dez"
                                                                       :amount 12000}]
                                                           :extra    [{:title  "Jan"
                                                                       :amount 0}
                                                                      {:title  "Fev"
                                                                       :amount 0}
                                                                      {:title  "Mar"
                                                                       :amount 15000}
                                                                      {:title  "Abr"
                                                                       :amount 15000}
                                                                      {:title  "Mai"
                                                                       :amount 15000}
                                                                      {:title  "Jun"
                                                                       :amount 15000}
                                                                      {:title  "Jul"
                                                                       :amount 15000}
                                                                      {:title  "Ago"
                                                                       :amount 15000}
                                                                      {:title  "Set"
                                                                       :amount 15000}
                                                                      {:title  "Out"
                                                                       :amount 15000}
                                                                      {:title  "Nov"
                                                                       :amount 19000}
                                                                      {:title  "Dez"
                                                                       :amount 12000}]}
    (provided
      (controller.revenue/revenue-for-year "2020" ..db..) => [{:title  "Jan"
                                                               :amount 0}
                                                              {:title  "Fev"
                                                               :amount 0}
                                                              {:title  "Mar"
                                                               :amount 15000}
                                                              {:title  "Abr"
                                                               :amount 15000}
                                                              {:title  "Mai"
                                                               :amount 15000}
                                                              {:title  "Jun"
                                                               :amount 15000}
                                                              {:title  "Jul"
                                                               :amount 15000}
                                                              {:title  "Ago"
                                                               :amount 15000}
                                                              {:title  "Set"
                                                               :amount 15000}
                                                              {:title  "Out"
                                                               :amount 15000}
                                                              {:title  "Nov"
                                                               :amount 19000}
                                                              {:title  "Dez"
                                                               :amount 12000}]
      (controller.fixed/fixed-expenses-for-year "2020" ..db..) => [{:title  "Jan"
                                                                    :amount 0}
                                                                   {:title  "Fev"
                                                                    :amount 0}
                                                                   {:title  "Mar"
                                                                    :amount 15000}
                                                                   {:title  "Abr"
                                                                    :amount 15000}
                                                                   {:title  "Mai"
                                                                    :amount 15000}
                                                                   {:title  "Jun"
                                                                    :amount 15000}
                                                                   {:title  "Jul"
                                                                    :amount 15000}
                                                                   {:title  "Ago"
                                                                    :amount 15000}
                                                                   {:title  "Set"
                                                                    :amount 15000}
                                                                   {:title  "Out"
                                                                    :amount 15000}
                                                                   {:title  "Nov"
                                                                    :amount 19000}
                                                                   {:title  "Dez"
                                                                    :amount 12000}]
      (controller.purchases/variable-purchases-for-year "2020" ..db..) => [{:title  "Jan"
                                                                            :amount 0}
                                                                           {:title  "Fev"
                                                                            :amount 0}
                                                                           {:title  "Mar"
                                                                            :amount 15000}
                                                                           {:title  "Abr"
                                                                            :amount 15000}
                                                                           {:title  "Mai"
                                                                            :amount 15000}
                                                                           {:title  "Jun"
                                                                            :amount 15000}
                                                                           {:title  "Jul"
                                                                            :amount 15000}
                                                                           {:title  "Ago"
                                                                            :amount 15000}
                                                                           {:title  "Set"
                                                                            :amount 15000}
                                                                           {:title  "Out"
                                                                            :amount 15000}
                                                                           {:title  "Nov"
                                                                            :amount 19000}
                                                                           {:title  "Dez"
                                                                            :amount 12000}]
      (controller.purchases/extra-purchases-for-year "2020" ..db..) => [{:title  "Jan"
                                                                         :amount 0}
                                                                        {:title  "Fev"
                                                                         :amount 0}
                                                                        {:title  "Mar"
                                                                         :amount 15000}
                                                                        {:title  "Abr"
                                                                         :amount 15000}
                                                                        {:title  "Mai"
                                                                         :amount 15000}
                                                                        {:title  "Jun"
                                                                         :amount 15000}
                                                                        {:title  "Jul"
                                                                         :amount 15000}
                                                                        {:title  "Ago"
                                                                         :amount 15000}
                                                                        {:title  "Set"
                                                                         :amount 15000}
                                                                        {:title  "Out"
                                                                         :amount 15000}
                                                                        {:title  "Nov"
                                                                         :amount 19000}
                                                                        {:title  "Dez"
                                                                         :amount 12000}])))